/**
 * Vercel serverless entrypoint.
 *
 * Vercel treats every file under this top-level `/api` directory as a
 * function. `vercel.json` routes all `/api/*` and `/health/*` traffic here,
 * and Hono does its own routing from there — so the whole API is one function
 * rather than one per endpoint, which keeps a single `pg` pool per warm
 * instance instead of one per route.
 *
 * The app is imported from a pre-built bundle rather than from source; see
 * `scripts/build-api-bundle.mjs` for why. The bundle is generated by the
 * build command and is not checked in.
 *
 * The Node runtime is not optional — `pg` needs raw TCP — which is also why
 * this uses `@hono/node-server/vercel` and not `hono/vercel`. The latter
 * targets the Web-standard runtime and expects a `Request`; on the Node
 * runtime it fails at request time with `this.raw.headers.get is not a
 * function`.
 */

import { handle } from "@hono/node-server/vercel";
import type { IncomingMessage, ServerResponse } from "node:http";
import { Readable } from "node:stream";
import { app } from "../apps/api/dist/app.bundle.cjs";

export const config = {
  runtime: "nodejs",
  // Triage calls the Anthropic API, which can outlast the 10s default.
  maxDuration: 60,
};

const honoHandler = handle(app);

type VercelRequest = IncomingMessage & { body?: unknown };

/**
 * Vercel's Node launcher runs with `shouldAddHelpers: true`: it reads the
 * request body itself and exposes the parsed value as `req.body`. That leaves
 * the underlying stream consumed, and the adapter — which builds a Web
 * `Request` by piping that stream — then waits on data that will never
 * arrive. The function hangs until the platform kills it.
 *
 * The symptom is specific and easy to misread: requests *without* a body are
 * fine, so `/health` and every GET look perfectly healthy while every login
 * and every claim submission times out.
 *
 * So we put the bytes back: rebuild a readable stream carrying the body the
 * helpers already consumed, and graft the original request's metadata onto it
 * before handing it to the adapter.
 */
export default function handler(req: VercelRequest, res: ServerResponse) {
  if (req.body === undefined || req.body === null) {
    return honoHandler(req, res);
  }

  const raw = Buffer.isBuffer(req.body)
    ? req.body
    : typeof req.body === "string"
      ? Buffer.from(req.body)
      : Buffer.from(JSON.stringify(req.body));

  const replayed = Readable.from([raw]) as unknown as IncomingMessage;

  Object.assign(replayed, {
    headers: { ...req.headers, "content-length": String(raw.byteLength) },
    headersDistinct: req.headersDistinct,
    rawHeaders: req.rawHeaders,
    method: req.method,
    url: req.url,
    httpVersion: req.httpVersion,
    httpVersionMajor: req.httpVersionMajor,
    httpVersionMinor: req.httpVersionMinor,
    socket: req.socket,
  });

  return honoHandler(replayed, res);
}
