/**
 * Vercel serverless entrypoint.
 *
 * Vercel treats every file under this top-level `/api` directory as a
 * function. `vercel.json` routes all `/api/*` and `/health` traffic here, and
 * Hono does its own routing from there — so the whole API is one function
 * rather than one per endpoint, which keeps a single `pg` pool per warm
 * instance instead of one per route.
 *
 * The app is imported from a pre-built bundle rather than from source; see
 * `scripts/build-api-bundle.mjs` for why. The bundle is generated by the
 * build command and is not checked in.
 *
 * The Node runtime (not Edge) is required: `pg` needs raw TCP.
 */

/*
 * `@hono/node-server/vercel`, not `hono/vercel`. The latter is for the
 * Web-standard (Edge) runtime and expects a `Request`; this function runs on
 * the Node runtime, which hands the handler Node's `req`/`res`. Using the
 * wrong one fails at request time, not build time, with
 * `this.raw.headers.get is not a function`.
 *
 * The Node runtime is not optional here — `pg` needs raw TCP.
 */
import { handle } from "@hono/node-server/vercel";
import { app } from "../apps/api/dist/app.bundle.cjs";

export const config = {
  runtime: "nodejs",
  // Triage calls the Anthropic API, which can outlast the 10s default.
  maxDuration: 60,
};

export default handle(app);
