/**
 * Vercel serverless entrypoint.
 *
 * Vercel treats every file under this top-level `/api` directory as a
 * function. `vercel.json` routes all `/api/*` and `/health/*` traffic here,
 * and Hono does its own routing from there — so the whole API is one function
 * rather than one per endpoint, which keeps a single `pg` pool per warm
 * instance instead of one per route.
 *
 * The app is imported from a pre-built bundle rather than from source; see
 * `scripts/build-api-bundle.mjs` for why. The bundle is generated by the
 * build command and is not checked in.
 *
 * The Node runtime is not optional — `pg` needs raw TCP — which is also why
 * this uses `@hono/node-server/vercel` and not `hono/vercel`. The latter
 * targets the Web-standard runtime and expects a `Request`; on the Node
 * runtime it fails at request time with `this.raw.headers.get is not a
 * function`.
 *
 * ---------------------------------------------------------------------------
 * `NODEJS_HELPERS=0` must stay set on the project, and it is not optional.
 *
 * By default Vercel's Node launcher wraps the handler with helpers that read
 * the request body themselves and expose a parsed value on `req.body`. That
 * leaves the underlying stream drained, and this adapter builds its Web
 * `Request` by piping that stream, so it waits forever on bytes that already
 * went elsewhere. The function hangs until the platform kills it.
 *
 * The symptom is badly misleading. Requests without a body are unaffected, so
 * `/health` and every GET look perfectly healthy while every login, claim
 * submission, and file upload times out with nothing in the log but a platform
 * timeout.
 *
 * Replaying the bytes out of `req.body` only half works: the helpers parse
 * JSON and urlencoded but hand back nothing for multipart, which is why file
 * upload stayed broken after login was fixed. Turning the helpers off is the
 * real fix, and the stream then arrives intact for every content type.
 *
 * The flag is read at *build* time, not runtime, and only as an environment
 * variable — `config.helpers` in the source file is not consulted. See
 * @vercel/node: shouldAddHelpers = !(config.helpers === false ||
 * process.env.NODEJS_HELPERS === "0"). `scripts/check-build-output.mjs`
 * asserts the built function has it off, because losing it silently breaks
 * every write path in the product.
 * ---------------------------------------------------------------------------
 */

import { handle } from "@hono/node-server/vercel";
import { app } from "../apps/api/dist/app.bundle.cjs";

export const config = {
  runtime: "nodejs",

  // Triage calls the Anthropic API, which can outlast the 10s default.
  maxDuration: 60,
};

export default handle(app);
